#!/bin/bash

set -e

binary_url="https://gitlab.crown.tech/crown/crown-core/uploads/2a23ec71a71f45078b580ca47447248b/crownd.tar.gz"
#binary_url="" # uncomment this line if you want to copy file from ~/zzz-crown-binaries rather than download

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
platform=`uname -a | awk '{print tolower($1)}'`
arch=`uname -m`

if [ "${platform}" == "linux" ]; then
    if [ "${arch}" == "x86_32" ]; then
        echo "Crown binary distribution not available for 32-bit platform"
        exit -1
    fi
elif [ "${platform}" == "darwin" ]; then
    echo "Crown binary distribution not available for macOS"
    exit -1
else
    echo "Crown binary distribution not available for your platform"
    exit -1
fi

cd "${root_dir}/bin"

if [ "${binary_url}" == "" ]; then
    cp ~/zzz-crown-binaries/crownd ./bitcoind
    exit 0
fi

echo "Downloading crown: ${binary_url}"
curl -L "${binary_url}" > crownd.tar.gz

echo "Unpacking crown distribution"
tar -x -f crownd.tar.gz
rm crownd.tar.gz
mv crownd bitcoind

exit 0
