#!/bin/bash

set -e

tag="bitcore-bin-001"
#tag="" # uncomment this line if you want to copy file from ~/zzz-crown-binaries rather than download

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
platform=`uname -a | awk '{print tolower($1)}'`
arch=`uname -m`
url="https://github.com/zhanzhenzhen/crowncoin/releases/download"

if [ "${platform}" == "linux" ]; then
    if [ "${arch}" == "x86_64" ]; then
    elif [ "${arch}" == "x86_32" ]; then
        echo "Crown binary distribution not available for 32-bit platform"
        exit -1
    fi
elif [ "${platform}" == "darwin" ]; then
    echo "Crown binary distribution not available for macOS"
    exit -1
else
    echo "Crown binary distribution not available for your platform"
    exit -1
fi

cd "${root_dir}/bin"

if [ "${tag}" == "" ]; then
    cp ~/zzz-crown-binaries/crownd ./bitcoind
    exit 0
fi

binary_url="${url}/${tag}/crownd.tar.gz"

echo "Downloading crown: ${binary_url}"
curl -L "${binary_url}" > crownd.tar.gz

echo "Unpacking crown distribution"
tar -x -f crownd.tar.gz
rm crownd.tar.gz
mv crownd bitcoind

exit 0
